#!/usr/bin/env sh
set -ex # Stop on first error and log all commands

CC="cc"
CFLAGS="-std=c99 -Wall -Wextra -Wshadow -Wmissing-declarations -Wswitch-enum -Wno-deprecated-declarations -pedantic"

$CC $CFLAGS -c nap.c

$CC $CFLAGS -o uri.t uri.t.c && ./uri.t	# Build and run tests for uri.h
$CC $CFLAGS -o nap main.c nap.o -lssl -lcrypto
