#!/usr/bin/env sh
set -ex # Stop on first error and log all commands

CC="cc"
CFLAGS="-std=c99 -Wall -Wextra -Wshadow -Wmissing-declarations -Wswitch-enum -Wno-deprecated-declarations -pedantic"

$CC $CFLAGS -c rrr.c
$CC $CFLAGS -o rrr main.c rrr.o -lssl -lcrypto
